### ISSUE TITLE
Add support for getting accounting data

### ISSUE THREAD

**Issue by tvuotila** [fastmonkeys/netvisor.py#6]
Netvisor has an API for [accounting materials](https://netvisor.zendesk.com/hc/fi/articles/201993983-Resources-Accounting-materials).

I will start adding support for [get account data](https://netvisor.zendesk.com/hc/fi/articles/201993983-Resources-Accounting-materials#ankkuri1).

**Comment by jpvanhal** [comment]
I released v0.7.0 with the account list support.
